/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package currency.converter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.ByteArrayInputStream;

class AppTest {
    @Test
    void appConvert() {
        String userInput = "convert USD AUD 100";
        System.setIn(new ByteArrayInputStream(userInput.getBytes()));
        String expected = "The conversion of 100.0 USD is: 133.0 AUD";
    }
}
