/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package currency.converter;

public class App {
    public static void main(String[] args) {
        // Check admin

        // Input Loop from user
        Scanner sc = new Scanner(system.in);
    }
}
