/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package currency.converter;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
