/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package currency.converter;

import java.time.LocalDate;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        // Check admin

        // Input Loop from user
        CurrencyHandler handler = new CurrencyHandler(true);
        Scanner sc = new Scanner(System.in);

        String input = "";

        Boolean exitFlag = false;

        do {
            System.out.println("Please input your command: ");
            input = sc.nextLine();

            // Break up input
            String[] input_list = input.split(" ");
            String command = input_list[0];

            switch (command) {
                case "convert":
                    System.out.println("Prints");
                    break;
                case "exit":
                    System.out.println("Have a good day!");
                    exitFlag = true;
                    break;
                default:
                    System.out.println("The command you've entered is invalid.");
            }

        } while (!exitFlag);

        Scanner s = new Scanner(System.in);
    }
}
